### ISSUE TITLE
Not working when i use @jhon.234 (dot)

### ISSUE THREAD

**Issue by moinkhan780** [Crazelu/fluttertagger#10]
Please make it possible to use dots, underscores in usernames.

**Comment by Crazelu** [comment]
@moinkhan780 you should be able to do this. There’s a property of the FlutterTagger constructor called **searchRegex** that you can specify to allow all kinds of characters. By default the regex is `^[a-zA-Z-]*$` which only matches letters of the English alphabet.

**Comment by ganadevprajapathy** [comment]
I tried adding regex for space but it does not seem to have color highlight on tags with space.

**Comment by Crazelu** [comment]
@ganadevprajapathy apart from the search regex, there's another regex used to match and format tags
https://github.com/Crazelu/fluttertagger/blob/2786c9dcd0de9a22a701f51950ac8bcd0bf37797/lib/src/tagger.dart#L955

You also need to look at the `tagTextFormatter`.
If you've not provided your own formatting rules via `tagTextFormatter` and an accompanying regex via `FlutterTaggerController.formatTags()`, then defaults are used which do not allow spacing in tags.

What to do:

After adding a tag using the controller, call `formatTags` on the controller, pass it your regex which extracts tag name and ID with space allowed. You may also need to pass it a `parser`. You can see how that is implemented below for the default format:

https://github.com/Crazelu/fluttertagger/blob/2786c9dcd0de9a22a701f51950ac8bcd0bf37797/lib/src/tagger.dart#L956

**Comment by flodaniel** [comment]
I am trying very hard to getting this to work but I can't figure it out. I can't use whitespace in the "name" property of a tag. Is it possible for you to provide a working example?
