### ISSUE TITLE
When manually selecting text and choosing "Select All," an error occurs.

### ISSUE THREAD

**Issue by LiangLuDev** [Crazelu/fluttertagger#12]
Range end 15 is out of text of length 14
'package:flutter/src/services/text_input.dart':
Failed assertion: line 968 pos 12: 'range.end >= 0 && range.end <= text.length'

**Comment by Crazelu** [comment]
Nice catch @LiangLuDev!
I'm able to reproduce the issue and isolate the cause. I was erroneously adding an extra space from `_buildTextSpan` in `FlutterTaggerController` which makes the text length greater than the valid selection range by 1.

This should be fixed in the next version.

**Comment by Crazelu** [comment]
@LiangLuDev this is now fixed in [v2.2.1](https://pub.dev/packages/fluttertagger/versions/2.2.1).
I'll be closing this now.

**Comment by JYeop** [comment]
It happens 2.3.1 again.

**Comment by Crazelu** [comment]
Can you confirm if it works just fine in v2.2.1? @JYeop
