### ISSUE TITLE
If the tag has a space, formatTags not working

### ISSUE THREAD

**Issue by Amber916Young** [Crazelu/fluttertagger#14]
update 
There is no issue here. I figure it out.

```
Hello again, I found another bug in this plugin.
for example: 
Here is my tag(all from backend data)
#hello world #helloword

when I call .formatTags(), only the second one can be formatted.
```

**Comment by Amber916Young** [comment]
Here is another issue I found it. 
For example, here is my text

<img width="220" alt="image" src="https://github.com/user-attachments/assets/836f8ae0-69dd-4713-a0b8-cadf09da7a40">

if the cursor is in the middle of hello and word, click any emoji, always add to the end.

**Comment by Amber916Young** [comment]
Here is another issue I found it. 
For example, here is my text

<img width="220" alt="image" src="https://github.com/user-attachments/assets/836f8ae0-69dd-4713-a0b8-cadf09da7a40">

if the cursor is in the middle of hello and word, click any emoji, and always add to the end.

but I don’t think it's the bug, my solution is that find the offset and insert it. however  the len of formattedText and text is different, I am still trying figure it out how to insert the correct position.

```
 final int cursorPosition = _contentTextController.selection.baseOffset;
 String formattedText = _contentTextController.formattedText;
 String newText ='${formattedText.substring(0, cursorPosition)}#${formattedText.substring(cursorPosition)}';
```

**Comment by flodaniel** [comment]
@Amber916Young what is the correct way to work with spaces in a tag? I am having the same problem.

**Comment by dpapayas** [comment]
you can change it in the _buildTextSpan and _formattedText function and reformat the splitter text @flodaniel @Amber916Young 

<img width="469" alt="Screenshot 2024-08-31 at 09 19 17" src="https://github.com/user-attachments/assets/dd68ef93-0140-457f-adb7-a182915fee03">

**Comment by flodaniel** [comment]
Both are private functions. Does the package just not offer formatting of values with special characters in between without having to dive deeper into the implementation/overriding the existing implementation?

**Comment by Crazelu** [comment]
Hi folks. I’ve been following this conversation via email notifications. I’m currently swamped with my 9-5 but I thought to pop in and drop this.
I’m going to respond to everyone in a few hours.

**Comment by flodaniel** [comment]
> Hi folks. I’ve been following this conversation via email notifications. I’m currently swamped with my 9-5 but I thought to pop in and drop this. I’m going to respond to everyone in a few hours.

Appreciate you taking the time! I am looking forward to seeing your approach :)

**Comment by Crazelu** [comment]
Apologies folks, a few hours turned into days.

**Comment by Crazelu** [comment]
@flodaniel currently, it's impossible to get tags with whitespaces to work.
You can currently update the search regex to allow for whitespaces to be a part of the search query. But the added tag will not be treated correctly because the current implementation splits the text by whitespace before trying to format the tags.

That was an assumption I made that tags wouldn't have whitespace. I have an idea to fix it. It'll involve doing an autocomplete suggestive search with the trie which would allow for whitespaces and other kinds of characters, really.
That may take me some time to implement. If you want to take a stab at this and submit a PR, you're more than welcome.

You can check out an implementation of prefix autocompletion with the trie [here](https://github.com/Crazelu/data-structures/blob/main/trie/trie.dart)

**Comment by Crazelu** [comment]
@Amber916Young I'm thinking I can introduce a `cursorPosition` getter which will be corresponding position of the cursor in the formatted text and with that you can do something like:

```dart
 onTap: (emoji) {
      final cursorPosition = controller.cursorPosition;
      final substring =
          controller.formattedText.substring(0, cursorPosition);
      final newText = substring +
          emoji +
          controller.formattedText.substring(cursorPosition);
      
      controller.text = newText;
      controller.selection = TextSelection.fromPosition(
        TextPosition(offset: controller.text.length),
      );
      controller.formatTags();
  },
```

That should fix the issue for you. Let me know if you think otherwise.

**Comment by Crazelu** [comment]
@Amber916Young I have introduced `cursorPosition` in [v2.2.1](https://pub.dev/packages/fluttertagger/versions/2.2.1) which tells the position of the cursor in the formatted text.

I've also updated the emoji onTap function in the example.

```dart
onTap: (emoji) {
    final baseOffset = controller.selection.baseOffset;
    final cursorPosition = controller.cursorPosition;
    final substring = controller.formattedText
        .substring(0, cursorPosition);
    final newText = substring +
        emoji +
        controller.formattedText.substring(cursorPosition);

    controller.text = newText;
    controller.formatTags();

    controller.selection = TextSelection.fromPosition(
      TextPosition(offset: baseOffset + emoji.length),
    );
  },
```

It's important to set the `TextSelection` relative to the base offset of the previous selection.

**Comment by flodaniel** [comment]
> @flodaniel currently, it's impossible to get tags with whitespaces to work. You can currently update the search regex to allow for whitespaces to be a part of the search query. But the added tag will not be treated correctly because the current implementation splits the text by whitespace before trying to format the tags.
> 
> That was an assumption I made that tags wouldn't have whitespace. I have an idea to fix it. It'll involve doing an autocomplete suggestive search with the trie which would allow for whitespaces and other kinds of characters, really. That may take me some time to implement. If you want to take a stab at this and submit a PR, you're more than welcome.
> 
> You can check out an implementation of prefix autocompletion with the trie [here](https://github.com/Crazelu/data-structures/blob/main/trie/trie.dart)

Hi @Crazelu, thanks for your reply and working on this. 
In the meantime I managed to resolve it replacing all whitespace with a non-whitespace, but looks like whitespace character:
` final bugfixedText = displayedText.replaceAll(' ', '\u00A0');`

**Comment by Amber916Young** [comment]
> @Amber916Young I have introduced `cursorPosition` in [v2.2.1](https://pub.dev/packages/fluttertagger/versions/2.2.1) which tells the position of the cursor in the formatted text.
> 
> I've also updated the emoji onTap function in the example.
> 
> ```dart
> onTap: (emoji) {
>     final baseOffset = controller.selection.baseOffset;
>     final cursorPosition = controller.cursorPosition;
>     final substring = controller.formattedText
>         .substring(0, cursorPosition);
>     final newText = substring +
>         emoji +
>         controller.formattedText.substring(cursorPosition);
> 
>     controller.text = newText;
>     controller.formatTags();
> 
>     controller.selection = TextSelection.fromPosition(
>       TextPosition(offset: baseOffset + emoji.length),
>     );
>   },
> ```
> 
> It's important to set the `TextSelection` relative to the base offset of the previous selection.

Thanks for your reply, I am testing the plugin

**Comment by Crazelu** [comment]
> > @flodaniel currently, it's impossible to get tags with whitespaces to work. You can currently update the search regex to allow for whitespaces to be a part of the search query. But the added tag will not be treated correctly because the current implementation splits the text by whitespace before trying to format the tags.
> > That was an assumption I made that tags wouldn't have whitespace. I have an idea to fix it. It'll involve doing an autocomplete suggestive search with the trie which would allow for whitespaces and other kinds of characters, really. That may take me some time to implement. If you want to take a stab at this and submit a PR, you're more than welcome.
> > You can check out an implementation of prefix autocompletion with the trie [here](https://github.com/Crazelu/data-structures/blob/main/trie/trie.dart)
> 
> Hi @Crazelu, thanks for your reply and working on this. In the meantime I managed to resolve it replacing all whitespace with a non-whitespace, but looks like whitespace character:
> 
> ```dart
>           final bugfixedText = displayedText.replaceAll(' ', '\u00A0');
> 
>           tagController.addTag(id: connectedUser.username, name: bugfixedText);
> ```

This is a clever hack!

**Comment by Crazelu** [comment]
> > @Amber916Young I have introduced `cursorPosition` in [v2.2.1](https://pub.dev/packages/fluttertagger/versions/2.2.1) which tells the position of the cursor in the formatted text.
> > I've also updated the emoji onTap function in the example.
> > ```dart
> > onTap: (emoji) {
> >     final baseOffset = controller.selection.baseOffset;
> >     final cursorPosition = controller.cursorPosition;
> >     final substring = controller.formattedText
> >         .substring(0, cursorPosition);
> >     final newText = substring +
> >         emoji +
> >         controller.formattedText.substring(cursorPosition);
> > 
> >     controller.text = newText;
> >     controller.formatTags();
> > 
> >     controller.selection = TextSelection.fromPosition(
> >       TextPosition(offset: baseOffset + emoji.length),
> >     );
> >   },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's important to set the `TextSelection` relative to the base offset of the previous selection.
> 
> Thanks for your reply, I am testing the plugin

Great!
I’ll be closing this now. You can reopen with a comment if there’s still an issue here.
