### ISSUE TITLE
Autocomplete suggestion is not saved (Android)

### ISSUE THREAD

**Issue by Aqua-Ye** [Crazelu/fluttertagger#16]
I'm testing the example on Android, when I swipe to autocomplete / suggest a word, the word is not saved, so when I press send, the `controller.formattedText` only gives me the previous formatted text. The `controller.text` does give me the correct text though.

Here is a video:

https://github.com/user-attachments/assets/7effae5d-c20e-409b-bf33-d1aa5400eaf6

**Comment by Crazelu** [comment]
Thanks for reporting this issue.
It is now fixed in [v2.3.1](https://pub.dev/packages/fluttertagger/versions/2.3.1)
