### ISSUE TITLE
No method for getting already-added tags

### ISSUE THREAD

**Issue by sayantan-poddar06** [Crazelu/fluttertagger#17]
**Method for adding tags:**
```
  void addTag({required String id, required String name}) {
    _addTagCallback?.call(id, name);
  }
```
 **Usage**
```
   taggerController.addTag(
        id: result.userId.toString(),
        name: result.firstName,
      );
```

now, if we want to get only added tags by the controller, there is no such method! It'll be a huge W for us, the developers!

**Comment by Crazelu** [comment]
This is now supported in [v2.3.1](https://pub.dev/packages/fluttertagger/versions/2.3.1).
`FlutterTaggerController.tags`
