### ISSUE TITLE
defect

### ISSUE THREAD

**Issue by admin924** [Crazelu/fluttertagger#2]
Hi @63a27531b866ce0016f9e582#crazelu#. Please call me 

How to automatically display in a text box after initState

**Comment by Crazelu** [comment]
@admin924 thanks for opening this issue.
This has now been included in [v1.0.0+6](https://pub.dev/packages/fluttertagger/versions/1.0.0+6).
You can create a FlutterTaggerController like so:
```dart
 FlutterTaggerController(
    text: "Hey @11a27531b866ce0016f9e582#brad#",
  )
```

And FlutterTagger will automatically format the tags.
You can also set the text value of the controller anywhere else you like but must call `formatTags` on the controller for the formatting to happen.

 ```dart
controller.text = "Hey @11a27531b866ce0016f9e582#brad#";
controller.formatTags();
```

Closing this now that it has been resolved.
